/*
Author: Donavan Sirois
Date: March 4, 2026
File name: mapreader.cpp
Description: Code of the map loader called upon starting the game. We are reading files in a very simplified
            version of the UDMF format, which is an easy to read .txt format of the original WAD doom files.
            These maps are created by hand, by us, programmers, but the .txt files are generated by AI to save
            time on translating everything.
Modifications:
*/

#include "mapreader.h"

bool MapReader::load(std::string fileName)
{
    std::ifstream mapWad(fileName);
    if (!mapWad.is_open()) return false;

    verteces.clear();
    linedefs.clear();
    sectors.clear();

    std::string word;
    while (mapWad >> word)
    {
        if (word == "vertex")
        {
            float value;
            Vertex v;
            mapWad >> value; // Skip reading the ID
            mapWad >> value;
            v.x = value;
            mapWad >> value;
            v.y = value;
            verteces.push_back(v);
        }
        else if (word == "linedef")
        {
            int value;
            Linedef l;
            mapWad >> value; // Skip reading the ID
            mapWad >> value;
            l.start = value;
            mapWad >> value;
            l.end = value;
            mapWad >> value;
            l.sideFront = value;
            mapWad >> value;
            l.sideBack = value;

            std::string twoSided;
            mapWad >> twoSided;
            l.twoSided = (twoSided == "true");
            linedefs.push_back(l);
        }
        else if (word == "sector")
        {
            float value;
            Sector s;
            mapWad >> value; // Skip reading the ID
            mapWad >> value;
            s.ceilingHeight = value;
            mapWad >> value;
            s.floorHeight = value;
            sectors.push_back(s);
        }

        word.clear();
    }

    // assign vectors to sectors
    for (int i = 0; i < sectors.size(); i++)
    {
        for (int j = 0; j < linedefs.size(); j++)
        {
            if (linedefs[j].sideFront == i) sectors[i].linedefs.push_back(j);

            if (linedefs[j].sideBack == i) sectors[i].linedefs.push_back(j);
        }
    }

    return true;
}
